name: Deploy Hugo site

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the current repo to the remote runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest

      # Get the README from 'leafboo/c-tcp-sockets' repository 
      - name: Checkout different repo
        uses: actions/checkout@v4
        with:
          repository: leafboo/c-tcp-sockets
          path: tmp
          sparse-checkout: |
            README.md
            images
          sparse-checkout-cone-mode: false 

      # Append the contents in the README to content/c-tcp.sockets.md 
      - name: Append the contents of the README to the markdown in content/
        run: cat tmp/README.md >> content/posts/c-tcp-sockets.md

      # Move the image directory in tmp/ to public/
      - name: Move images/ into public/
        run: mv tmp/images public/

      # Build the site
      - name: Build
        run: hugo --minify

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5 

      # Upload generated files
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Deploy to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4 
