name: Deploy Hugo site

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  initialization:
    strategy:
      matrix:
        repository: [leafboo/c-tcp-sockets]

    runs-on: ubuntu-latest

    steps: 
      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest


      # Get the README and images/ from the matrix 'repository'
      - name: Checkout different repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          path: tmp
          sparse-checkout: |
            README.md
            images
          sparse-checkout-cone-mode: false 

      # Append both the text contents from README in tmp/ and the link to the github repo to the Hugo markdown
      - name: Append texts to the Hugo markdown
        run: |
          mkdir content
          repository_name="$(echo ${OWNER_AND_REPOSITORY_NAME} | sed 's/leafboo\///g')"
          hugo new content/${repository_name}.md
          cat tmp/README.md >> content/${repository_name}.md
          mv tmp/images .
          rm -rf tmp
          github_repo_link="<br><br><br>
          Link to GitHub repo: <https://github.com/${OWNER_AND_REPOSITORY_NAME}>"
          echo ${github_repo_link} >> content/${repository_name}.md
        env:
          OWNER_AND_REPOSITORY_NAME: ${{ matrix.repository }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.repository }}


  build:
    needs: initialization
    runs-on: ubuntu-latest

    steps:
      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest

      # Clone the current repo to the remote runner
      - name: Checkout
        uses: actions/checkout@v4

      # TODO: get the artifacts from the previous job
      - name: Get artifacts from the initialization job
        uses: actions/download-artifact@v8
        with:
          path: initialization-artifacts/
          merge-multiple: true

      - name: List the downloaded artifacts
        run: |
          cat failhere.txt
          ls initialization-artifacts

      # TODO: move files from the artifact to the content/posts/ directory

      # Build the site
      # TODO: separate this to a build job (note: when a job depends on another job that uses matrix, it waits for all the matrix jobs to finish first before proceeding)
      - name: Build
        run: hugo --minify

      # Move the image directory in tmp/ to public/
      - name: Move images/ into public/
        run: mv tmp/images public/

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5 

      # Upload generated files
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Deploy to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4 
